/* Generated by Wrangler. Run `pnpm run types` after changing bindings. */
interface Env {
  DISCORD_BOT_TOKEN: string;
  DISCORD_PUBLIC_KEY: string;
  DISCORD_APPLICATION_ID: string;
  NINE_ROUTER_API_KEY: string;
  NINE_ROUTER_ADMIN_TOKEN: string;
  NINE_ROUTER_BASE_URL: string;
  NINE_ROUTER_MODEL: string;
  NINE_ROUTER_ALLOWED_MODELS?: string;
  DiscordBotAgent: DurableObjectNamespace<import("./src/index").DiscordBotAgent>;
}
